spring:
   jpa:
     database: mysql
     database-platform: org.hibernate.dialect.MySQL5Dialect
     show-sql: true
     hibernate:
       ddl-auto: update
   datasource:
   
   
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/venta
     username: root
     password:
     
